
redis:
   image: redis



voting:
  image: voting-app
  ports:
     - 80:80
  links:
     - redis

 
db:
  environment:
          - POSTGRES_HOST_AUTH_METHOD=trust 
  image: postgres:9.4

worker:
  image: worker-app
  links:
    - redis
    - db

result:
  image: result
  ports:
     - 81:80
  links:
     - db
